# 
# Copyright 2025 EDT&Partners
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 
resource "random_password" "this" {
  count   = var.type == "hex" || var.type == "base64" ? 1 : 0
  length  = 32
  special = false
  upper   = false
  lower   = true
  numeric = true
}

resource "aws_secretsmanager_secret" "this" {
  name        = var.name
  description = "Secret generated by Terraform"

}

resource "aws_secretsmanager_secret_version" "this" {
  secret_id = aws_secretsmanager_secret.this.id

  secret_string = var.type == "hex" || var.type == "base64" ? (
    var.type == "hex"
    ? replace(random_password.this[0].result, "[^a-f0-9]", "a")
    : base64encode(random_password.this[0].result)
  ) : var.custom_value

  depends_on = [random_password.this]
}


module "ssm_dynamic_variables" {
  source               = "cloudposse/ssm-parameter-store/aws"
  ignore_value_changes = true
  parameter_write = [
    {
      name        = "${var.name}_ARN"
      value       = aws_secretsmanager_secret.this.arn
      type        = "String"
      overwrite   = true
      description = ""
    }
  ]
}
