# © [2025] EDT&Partners. Licensed under CC BY 4.0.
resource "random_password" "this" {
  count   = var.type == "hex" || var.type == "base64" ? 1 : 0
  length  = 32
  special = false
  upper   = false
  lower   = true
  numeric = true
}

resource "aws_secretsmanager_secret" "this" {
  name        = var.name
  description = "Secret generated by Terraform"

}

resource "aws_secretsmanager_secret_version" "this" {
  secret_id = aws_secretsmanager_secret.this.id

  secret_string = var.type == "hex" || var.type == "base64" ? (
    var.type == "hex"
    ? replace(random_password.this[0].result, "[^a-f0-9]", "a")
    : base64encode(random_password.this[0].result)
  ) : var.custom_value

  depends_on = [random_password.this]
}


module "ssm_dynamic_variables" {
  source               = "cloudposse/ssm-parameter-store/aws"
  ignore_value_changes = true
  parameter_write = [
    {
      name        = "${var.name}_ARN"
      value       = aws_secretsmanager_secret.this.arn
      type        = "String"
      overwrite   = true
      description = ""
    }
  ]
}
